Repository PNUops/ops-mvp-back, pull requests merged in 2025-09, with the labels that each got.

#130 Feature/#127 수동 정렬 api 개발
  src/main/java/com/ops/ops/modules/contest/application/convenience/ContestConvenience.java
  src/main/java/com/ops/ops/modules/contest/domain/dao/ContestRepository.java
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamLikeConvenience.java
  src/main/java/com/ops/ops/modules/team/application/dto/request/TeamSortCustomRequest.java
  src/main/java/com/ops/ops/modules/team/domain/SortType.java
  src/main/java/com/ops/ops/modules/team/domain/Team.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamRepository.java
  src/main/java/com/ops/ops/modules/team/exception/TeamExceptionType.java
Labels: ⭐️ 기능 구현, ‼️ P1

#132 Bug/#131 정렬 시 unique 제약으로 인한 롤백 문제 해결
  src/main/java/com/ops/ops/modules/team/application/dto/request/TeamSortCustomRequest.java
  src/main/java/com/ops/ops/modules/team/domain/Team.java
Labels: 🐞 버그, ‼️ P1

#134 Feature/#133 팀 상세보기 지도교수 추가
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/dto/request/TeamCreateRequest.java
  src/main/java/com/ops/ops/modules/team/application/dto/request/TeamDetailUpdateRequest.java
  src/main/java/com/ops/ops/modules/team/application/dto/response/TeamDetailResponse.java
  src/main/java/com/ops/ops/modules/team/domain/Team.java
Labels: ⭐️ 기능 구현

#140 Feature/#139 팀 상세보기수정 관리자 null 가능 기능추가
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/dto/request/TeamDetailUpdateRequest.java
  src/main/java/com/ops/ops/modules/team/domain/Team.java
  src/main/java/com/ops/ops/modules/team/exception/TeamExceptionType.java
Labels: ⭐️ 기능 구현, 🔍 기능 수정

#138 Feature/#137 좋아요 투표 횟수 계정당 2회 제한 기능 구현
  src/main/java/com/ops/ops/modules/team/api/TeamLikeController.java
  src/main/java/com/ops/ops/modules/team/application/TeamLikeCommandService.java
  src/main/java/com/ops/ops/modules/team/application/dto/response/MemberLikeCountResponse.java
  src/main/java/com/ops/ops/modules/team/application/dto/response/TeamLikeToggleResponse.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamLikeRepository.java
  src/main/java/com/ops/ops/modules/team/exception/TeamLikeException.java
  src/main/java/com/ops/ops/modules/team/exception/TeamLikeExceptionType.java
Labels: ⭐️ 기능 구현, ‼️ P1
