Repository PNUops/ops-mvp-back, pull requests merged in 2025-07, with the labels that each got.

#72 Feature/#70 공지사항 curd api 개발
  src/main/java/com/ops/ops/modules/notice/api/NoticeController.java
  src/main/java/com/ops/ops/modules/notice/application/NoticeCommandService.java
  src/main/java/com/ops/ops/modules/notice/application/NoticeQueryService.java
  src/main/java/com/ops/ops/modules/notice/application/convenience/NoticeConvenience.java
  src/main/java/com/ops/ops/modules/notice/application/dto/request/NoticeRequest.java
  src/main/java/com/ops/ops/modules/notice/application/dto/response/NoticeDetailResponse.java
  src/main/java/com/ops/ops/modules/notice/application/dto/response/NoticeSummaryResponse.java
  src/main/java/com/ops/ops/modules/notice/domain/Notice.java
  src/main/java/com/ops/ops/modules/notice/domain/dao/NoticeRepository.java
  src/main/java/com/ops/ops/modules/notice/exception/NoticeException.java
  src/main/java/com/ops/ops/modules/notice/exception/NoticeExceptionType.java
Labels: ⭐️ 기능 구현

#69 Feature/#68 메인페이지의 대회의 전체 팀 조회
  src/main/java/com/ops/ops/modules/contest/api/ContestController.java
  src/main/java/com/ops/ops/modules/contest/application/ContestCommandService.java
  src/main/java/com/ops/ops/modules/contest/application/ContestQueryService.java
  src/main/java/com/ops/ops/modules/contest/domain/dao/ContestRepository.java
  src/main/java/com/ops/ops/modules/contest/domain/dao/ContestTeamRepository.java
  src/main/java/com/ops/ops/modules/contest/exception/ContestExceptionType.java
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamQueryService.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamRepository.java
Labels: ⭐️ 기능 구현

#75 Bug/#63 존재하지 않는 이미지 파일 삭제
  src/main/java/com/ops/ops/global/util/FileStorageUtil.java
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
Labels: 🐞 버그

#78 Feature/#76-구글-소셜-로그인/회원가입-구현
  src/main/java/com/ops/ops/global/security/SecurityConfig.java
  src/main/java/com/ops/ops/global/util/oauth/component/GoogleOauth.java
  src/main/java/com/ops/ops/global/util/oauth/component/SocialOauth.java
  src/main/java/com/ops/ops/global/util/oauth/dto/GoogleOAuthToken.java
  src/main/java/com/ops/ops/global/util/oauth/dto/GoogleUser.java
  src/main/java/com/ops/ops/global/util/oauth/exception/OAuthException.java
  src/main/java/com/ops/ops/global/util/oauth/exception/OAuthExceptionType.java
  src/main/java/com/ops/ops/modules/member/api/MemberController.java
  src/main/java/com/ops/ops/modules/member/application/MemberCommandService.java
Labels: ⭐️ 기능 구현

#82 Refactor/#77 관리자페이지 주요 기능들을 이번 대회 기준으로 바꾸기
  src/main/java/com/ops/ops/modules/contest/domain/dao/ContestRepository.java
  src/main/java/com/ops/ops/modules/team/application/TeamAdminQueryService.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamLikeRepository.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamRepository.java
Labels: 🔍 기능 수정

#93 Bug/#91 팀 삭제 시 팀장 권한 변경
  src/main/java/com/ops/ops/modules/member/application/convenience/MemberConvenience.java
  src/main/java/com/ops/ops/modules/member/domain/Member.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/TeamQueryService.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamMemberConvenience.java
Labels: 🐞 버그

#95 Refactor/#85 구글 소셜 로그인 - 프론트 개발 환경별 콜백 URL 동적 처리하기
  src/main/java/com/ops/ops/global/util/oauth/component/GoogleOauth.java
Labels: 🛠️ 리팩토링

#99 Refactor/#85 구글 콜백 URL PR 재업로드
  src/main/java/com/ops/ops/global/util/oauth/component/GoogleOauth.java
Labels: 🔍 기능 수정

#102 Feature/#101 대회 조회 시간 응답 형태 수정
  src/main/java/com/ops/ops/modules/contest/application/dto/response/ContestResponse.java
Labels: ⭐️ 기능 구현

#103 Bug/#100-팀-삭제-오류
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamCommentConvenience.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamLikeConvenience.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamMemberConvenience.java
  src/main/java/com/ops/ops/modules/team/domain/Team.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamCommentRepository.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamLikeRepository.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamMemberRepository.java
Labels: 🐞 버그

#110 Feature/#109 팀 정렬 방식 설정 api 개발
  src/main/java/com/ops/ops/modules/contest/application/ContestQueryService.java
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamLikeConvenience.java
  src/main/java/com/ops/ops/modules/team/application/convenience/TeamSortConvenience.java
  src/main/java/com/ops/ops/modules/team/application/dto/request/TeamSortRequest.java
  src/main/java/com/ops/ops/modules/team/domain/SortType.java
  src/main/java/com/ops/ops/modules/team/domain/TeamSort.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamSortRepository.java
  src/main/java/com/ops/ops/modules/team/exception/TeamExceptionType.java
Labels: ⭐️ 기능 구현

#114 fix : 투표참여율 분모값에서 가짜멤버 빼기
  src/main/java/com/ops/ops/modules/member/application/convenience/MemberConvenience.java
  src/main/java/com/ops/ops/modules/member/domain/Member.java
Labels: 🔍 기능 수정, 🛠️ 리팩토링
