Repository PNUops/ops-mvp-back, pull requests merged in 2025-06, with the labels that each got.

#44 Feature/#19 file 관련 사항 개발
  src/main/java/com/ops/ops/global/error/FileDeleteFailedException.java
  src/main/java/com/ops/ops/global/error/FileNotFoundException.java
  src/main/java/com/ops/ops/global/error/FileSaveFailedException.java
  src/main/java/com/ops/ops/global/util/FileStorageUtil.java
  src/main/java/com/ops/ops/modules/file/api/FileController.java
  src/main/java/com/ops/ops/modules/file/domain/dao/FileRepository.java
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
Labels: ⭐️ 기능 구현, ❗️P2

#42 Feature/#14 로그인 api 개발
  src/main/java/com/ops/ops/global/util/MailUtil.java
  src/main/java/com/ops/ops/modules/member/api/MemberController.java
  src/main/java/com/ops/ops/modules/member/application/MemberCommandService.java
  src/main/java/com/ops/ops/modules/member/application/MemberQueryService.java
  src/main/java/com/ops/ops/modules/member/application/dto/request/PasswordUpdateRequest.java
  src/main/java/com/ops/ops/modules/member/application/dto/request/SignInRequest.java
  src/main/java/com/ops/ops/modules/member/application/dto/request/SignUpRequest.java
  src/main/java/com/ops/ops/modules/member/application/dto/response/EmailFindResponse.java
  src/main/java/com/ops/ops/modules/member/application/dto/response/SignInResponse.java
  src/main/java/com/ops/ops/modules/member/domain/EmailAuth.java
  src/main/java/com/ops/ops/modules/member/domain/Member.java
  src/main/java/com/ops/ops/modules/member/domain/dao/EmailAuthRepository.java
  src/main/java/com/ops/ops/modules/member/domain/dao/MemberRepository.java
  src/main/java/com/ops/ops/modules/member/exception/MemberExceptionType.java
Labels: ⭐️ 기능 구현

#43 Feature/#4 팀 전체보기 조회 api 개발
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/TeamQueryService.java
  src/main/java/com/ops/ops/modules/team/application/dto/response/TeamSummaryResponse.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamLikeRepository.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamRepository.java
Labels: ⭐️ 기능 구현

#39 Feature/#22-팀 프리뷰 이미지 삭제 API개발
  .gitignore
  src/main/java/com/ops/ops/global/util/FileStorageUtil.java
  src/main/java/com/ops/ops/modules/file/domain/dao/FileRepository.java
  src/main/java/com/ops/ops/modules/file/exception/FileExceptionType.java
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/TeamQueryService.java
  src/main/java/com/ops/ops/modules/team/application/dto/request/PreviewDeleteRequest.java
Labels: ⭐️ 기능 구현

#40 Feature/#32 팀 프리뷰 이미지 조회 API개발
  src/main/java/com/ops/ops/modules/team/api/TeamController.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommandService.java
  src/main/java/com/ops/ops/modules/team/application/TeamQueryService.java
Labels: ⭐️ 기능 구현

#47 Feature/#7 투표 참여율 조회 api개발
  src/main/java/com/ops/ops/modules/team/api/TeamAdminController.java
  src/main/java/com/ops/ops/modules/team/application/TeamAdminQueryService.java
  src/main/java/com/ops/ops/modules/team/application/dto/response/TeamVoteRateResponse.java
  src/main/java/com/ops/ops/modules/team/domain/dao/TeamLikeRepository.java
Labels: ⭐️ 기능 구현

#48 Feature/46 댓글 조회 API 응답 수정
  src/main/java/com/ops/ops/modules/member/domain/dao/MemberRepository.java
  src/main/java/com/ops/ops/modules/team/application/TeamCommentQueryService.java
  src/main/java/com/ops/ops/modules/team/application/dto/response/TeamCommentResponse.java
Labels: 🔍 기능 수정, 🛠️ 리팩토링

#60 Refactor/#58 비회원은 댓글 조회가 안되도록 설정
  src/main/java/com/ops/ops/global/security/SecurityConfig.java
  src/main/java/com/ops/ops/modules/team/api/TeamCommentController.java
Labels: 🔍 기능 수정, 🛠️ 리팩토링
